version: '3.8'

x-airflow-common:
  &airflow-common
  build: .
  image: airflow-local:2.9.3
  environment:
    AIRFLOW_HOME: /opt/airflow
    # point to the script that defines a DAG object
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/orchestration
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__WEBSERVER__RBAC: 'true'
    AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8081
    OPENAQ_API_KEY: ${OPENAQ_API_KEY}
    CITY_NAME: ${CITY_NAME}
    CITY_LAT: ${CITY_LAT}
    CITY_LON: ${CITY_LON}
    WEATHER_FORECAST_DAYS: ${WEATHER_FORECAST_DAYS}
    WEATHER_TIMEZONE: ${WEATHER_TIMEZONE}
    DUCKDB_PATH: /opt/airflow/data/air_quality_weather.duckdb
    RAW_DATA_PATH_AIR_QUALITY: /opt/airflow/ingestion/raw_data/air_quality
    RAW_DATA_PATH_WEATHER: /opt/airflow/ingestion/raw_data/weather

  volumes:
    - ./orchestration:/opt/airflow/orchestration
    - ./ingestion:/opt/airflow/ingestion
    - ./transformation:/opt/airflow/transformation
    - ./data:/opt/airflow/data
    - ./logs:/opt/airflow/logs
    - ./visualization:/opt/airflow/visualization

  depends_on:
    postgres:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
    interval: 10s
    timeout: 10s
    retries: 5

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    # how Docker monitors the health of the PostgreSQL service container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
    # changed host to 8081 from 8080 because I was getting errors
      - "8081:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy


  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true
  
  streamlit:
    build: .
    command: streamlit run visualization/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/opt/airflow
    depends_on:
      postgres:
        condition: service_healthy



volumes:
  postgres_data:
  logs:
  dags_data:


