# transformation/aq_weather_dbt/profiles.yml
# This profiles.yml is for dbt running INSIDE the Docker container.

aq_weather_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Uncomment to run locally
      # path: '../../data/air_quality_weather.duckdb'
      # external_root: '../../ingestion/raw_data'
      path: "{{ env_var('DUCKDB_PATH', 'transformation/aq_weather_dbt/data/air_quality_weather.duckdb') }}"
      external_root: "{{ env_var('RAW_DATA_PATH', 'ingestion/raw_data') }}"
      schema: main
      external_tables:
        enabled: true
        file_format_options:
          json:
            auto_detect: true
