    # transformation/air_quality_dbt/profiles.yml
    # This profiles.yml is for dbt running INSIDE the Docker container.

air_quality_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Uncomment to run locally
      # path: './data/air_quality.duckdb'
      # external_root: './ingestion/raw_data'
      # Paths for Airflow run
      path: "{{ env_var('DUCKDB_PATH', './data/air_quality.duckdb') }}"
      external_root: "{{ env_var('RAW_DATA_PATH', './ingestion/raw_data') }}"
      external_tables:
        enabled: true
        file_format_options:
          json:
            auto_detect: true

    